### ISSUE TITLE
Bug: non-existant group in Api-Check blocks deletion

### ISSUE THREAD

**Issue by fluktuid** [checkly/checkly-operator#59]
When applying an api-check with a non-existant group, the check can't be deleted.
The deletion is blocked by the finalizer.

steps to reproduce:
- apply api-check with non-existant group
  e.g.
  ``` yaml
  apiVersion: k8s.checklyhq.com/v1alpha1
  kind: ApiCheck
  metadata:
    name: operator-apicheck-sample
  spec:
    endpoint: "checklyhq.com"
    success: "200"
    muted: true # Default "false"
    group: non-existant-dummy-group
  ```
- delete ApiCheck
   `kubectl delete apicheck operator-apicheck-sample`
 - look at operator logs and wait (potenially forever)

Workaround (bad practice):
- patch operator for deletion
  this may result in a delta between checkly api and cluster-scope, so this may result in a delta between 'expected reality' and 'reality' when using gitops.
  `kubectl  patch apicheck operator-apicheck-sample  --patch '{"metadata":{"finalizers":[]}}' --type='merge'`
